FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lockb ./

RUN bun install

COPY src src
COPY tsconfig.json .
COPY drizzle.config.ts .
COPY drizzle drizzle

ENV NODE_ENV dev
CMD ["bun", "dev"]

EXPOSE 3000 